<?php
return [
    'tabela' => 'DAT1',
    'campos' => [
        ['nome' => 'relacao_com_veiculo', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'estrangeiro', 'tipo' => 'boolean', 'padrao' => false],
        ['nome' => 'tipo_documento', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'numero_documento', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'pais', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'nome', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'cpf', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'profissao', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'sexo', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'data_nascimento', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'email', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'celular', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'cep', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'logradouro', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'numero', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'complemento', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'bairro_localidade', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'cidade', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'uf', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'data', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'horario', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'cidade_acidente', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'uf_acidente', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'cep_acidente', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'logradouro_acidente', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'numero_acidente', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'complemento_acidente', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'bairro_localidade_acidente', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'ponto_referencia_acidente', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'condicoes_via', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'sinalizacao_horizontal_vertical', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'tracado_via', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'condicoes_meteorologicas', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'tipo_acidente', 'tipo' => 'string', 'obrigatorio' => true],
    ],
    'status_apos_processo' => 'Em Andamento',
    'enviar_email' => false,
    'verificar_existente' => true
];
