<?php
return [
    'tabela' => 'DAT2',
    'campos' => [
        ['nome' => 'situacao_veiculo', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'placa', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'renavam', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'tipo_veiculo', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'chassi', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'uf_veiculo', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'cor_veiculo', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'marca_modelo', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'ano_modelo', 'tipo' => 'integer', 'obrigatorio' => true],
        ['nome' => 'ano_fabricacao', 'tipo' => 'integer', 'obrigatorio' => true],
        ['nome' => 'categoria', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'segurado', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'seguradora', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'veiculo_articulado', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'manobra_acidente', 'tipo' => 'string', 'obrigatorio' => true],
        ['nome' => 'nao_habilitado', 'tipo' => 'boolean', 'padrao' => false],
        ['nome' => 'numero_registro', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'uf_cnh', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'categoria_cnh', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'data_1habilitacao', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'validade_cnh', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'estrangeiro-condutor', 'tipo' => 'boolean', 'padrao' => false],
        ['nome' => 'tipo_documento_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'numero_documento_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'pais_documento_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'nome_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'cpf_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'sexo_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'nascimento_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'email_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'celular_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'cep_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'logradouro_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'numero_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'complemento_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'bairro_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'cidade_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'uf_condutor', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'danos-sistema-seguranca', 'tipo' => 'boolean', 'padrao' => false],
        ['nome' => 'partes_danificadas', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'danos_carga', 'tipo' => 'boolean', 'padrao' => false],
        ['nome' => 'numero_notas', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'tipo_mercadoria', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'valor_mercadoria', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'extensao_danos', 'tipo' => 'string', 'obrigatorio' => false],
        ['nome' => 'tem_seguro_carga', 'tipo' => 'boolean', 'padrao' => false],
        ['nome' => 'seguradora_carga', 'tipo' => 'string', 'obrigatorio' => false],
    ],
    'status_apos_processo' => 'Em Andamento',
    'enviar_email' => false,
    'verificar_existente' => true
];
